# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import example.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_datetime', models.DateTimeField(editable=False, null=True)),
                ('reference', models.CharField(default=example.models.interview_identifier, max_length=7, unique=True)),
                ('interview_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.TextField(max_length=100, verbose_name='Where is this interview being conducted?')),
                ('interviewed', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Subject'),
        ),
    ]
